'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert("artworks", [
      {
        token_id: 0,
        views: 11,
        is_selling: 0,
        price: 0,
        ipfsURI: "https://images.unsplash.com/photo-1634986666676-ec8fd927c23d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        title: "테스트작품1",
        desc: "테스트1 작품입니다",
        count_votes: 13,
        collaboration_id: 1,
        creator_id: 1,
        owner_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 141,
        is_selling: 1,
        price: 38,
        ipfsURI:   'https://images.unsplash.com/photo-1567359781514-3b964e2b04d6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=536&q=80',
        title: "테스트작품2",
        desc: "테스트2 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 2,
        owner_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 72,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
        title: "테스트작품3",
        desc: "테스트3 작품입니다",
        count_votes: 17,
        collaboration_id: 1,
        creator_id: 3,
        owner_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 85,
        is_selling: 1,
        price: 47,
        ipfsURI:   'https://images.unsplash.com/photo-1593073862407-a3ce22748763?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80',
        title: "테스트작품4",
        desc: "테스트4 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 4,
        owner_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 112,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1637416067365-2b5e7e8fe8fa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
        title: "테스트작품5",
        desc: "테스트5 작품입니다",
        count_votes: 27,
        collaboration_id: 1,
        creator_id: 5,
        owner_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 355,
        is_selling: 1,
        price: 85,
        ipfsURI:   'https://images.unsplash.com/photo-1634320714682-ae8b9c9cee60?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
        title: "테스트작품6",
        desc: "테스트6 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 6,
        owner_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 218,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1635399860495-2a2802a6df5e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
        title: "테스트작품7",
        desc: "테스트7 작품입니다",
        count_votes: 43,
        collaboration_id: 1,
        creator_id: 7,
        owner_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 215,
        is_selling: 1,
        price: 82,
        ipfsURI:   'https://images.unsplash.com/photo-1635322966219-b75ed372eb01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80',
        title: "테스트작품8",
        desc: "테스트8 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 8,
        owner_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 177,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1617396900799-f4ec2b43c7ae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
        title: "테스트작품9",
        desc: "테스트9 작품입니다",
        count_votes: 13,
        collaboration_id: 2,
        creator_id: 9,
        owner_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 58,
        is_selling: 1,
        price: 99,
        ipfsURI:   'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=882&q=80',
        title: "테스트작품10",
        desc: "테스트10 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 10,
        owner_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 77,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80',
        title: "테스트작품11",
        desc: "테스트11 작품입니다",
        count_votes: 72,
        collaboration_id: 2,
        creator_id: 11,
        owner_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 110,
        is_selling: 1,
        price: 1000,
        ipfsURI:   'https://images.unsplash.com/photo-1637666505754-7416ebd70cbf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
        title: "테스트작품12",
        desc: "테스트12 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 12,
        owner_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 212,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1622737133809-d95047b9e673?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2232&q=80',
        title: "테스트작품13",
        desc: "테스트13 작품입니다",
        count_votes: 23,
        collaboration_id: 2,
        creator_id: 13,
        owner_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 212,
        is_selling: 1,
        price: 44,
        ipfsURI:   'https://images.unsplash.com/photo-1635243824676-e2f0f45a88e8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGRpZ2l0YWwlMjBhcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60',
        title: "테스트작품14",
        desc: "테스트14 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 14,
        owner_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 116,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1547333590-47fae5f58d21?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
        title: "테스트작품15",
        desc: "테스트15 작품입니다",
        count_votes: 128,
        collaboration_id: 2,
        creator_id: 15,
        owner_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 41,
        is_selling: 1,
        price: 58,
        ipfsURI:   'https://images.unsplash.com/photo-1551732998-9573f695fdbb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
        title: "테스트작품16",
        desc: "테스트16 작품입니다",
        count_votes: 0,
        collaboration_id: null,
        creator_id: 16,
        owner_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 22,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1633743252577-ccb68cbdb6ed?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1548&q=80',
        title: "테스트작품16",
        desc: "테스트16 작품입니다",
        count_votes: 15,
        collaboration_id: 2,
        creator_id: 16,
        owner_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 1100,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1636889647964-c759d54751ef?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80',
        title: "테스트작품17",
        desc: "테스트17 작품입니다",
        count_votes: 130,
        collaboration_id: 3,
        creator_id: 17,
        owner_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 141,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1617791160536-598cf32026fb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1528&q=80',
        title: "테스트작품18",
        desc: "테스트18 작품입니다",
        count_votes: 35,
        collaboration_id: 3,
        creator_id: 18,
        owner_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 51,
        is_selling: 0,
        price: 0,
        ipfsURI:   'https://images.unsplash.com/photo-1635396259299-2eb9a880075a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80',
        title: "테스트작품19",
        desc: "테스트19 작품입니다",
        count_votes: 22,
        collaboration_id: 3,
        creator_id: 19,
        owner_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        token_id: 0,
        views: 42,
        is_selling: 0,
        price: 0,
        ipfsURI:    'https://images.unsplash.com/photo-1625014618427-fbc980b974f5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1528&q=80',
        title: "테스트작품20",
        desc: "테스트20 작품입니다",
        count_votes: 55,
        collaboration_id: 3,
        creator_id: 20,
        owner_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },


  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
